# -*- coding: utf-8 -*-
"""CA-T2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGVk9g8VsqfTxGJ5fIyAOtrrknbmBFRR
"""

import pandas as pd

df = pd.read_csv("netflix.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

print("Dataset Information:\n")
df.info()

print("Missing values:\n")
print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print("Rows before removing duplicates:", len(df))

df = df.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(df))
print("Duplicates remaining:", df.duplicated().sum())

df.describe()

print("Unique values in each column:\n")
print(df.nunique())

import matplotlib.pyplot as plt

df["rating"].value_counts().plot(kind="bar")

plt.title("Distribution of Netflix Content Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Titles")
plt.xticks(rotation=45)
plt.show()

# Number of titles released each year
year_counts = df["release_year"].value_counts().sort_index()

plt.figure(figsize=(12, 5))
plt.plot(year_counts.index, year_counts.values)

plt.title("Netflix Titles by Release Year")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")
plt.grid()
plt.show()

rating_counts = df["rating"].value_counts().head(10)

plt.figure(figsize=(10, 5))
rating_counts.plot(kind="bar")

plt.title("Most Common Netflix Content Ratings")
plt.xlabel("Content Rating")
plt.ylabel("Number of Titles")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 5))

plt.scatter(
    df["release_year"],
    df["user_rating_score"],
    alpha=0.5
)

plt.title("User Rating Score vs Release Year")
plt.xlabel("Release Year")
plt.ylabel("User Rating Score")

plt.show()

average_rating = df["user_rating_score"].mean()

print("Average User Rating:", round(average_rating, 2))
print("Highest User Rating:", df["user_rating_score"].max())
print("Lowest User Rating:", df["user_rating_score"].min())

top_10 = df[["title", "user_rating_score", "release_year"]].sort_values(
    by="user_rating_score",
    ascending=False
).head(10)

top_10

print("Final Dataset Shape:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

